// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc3gBw8pjXAwVwNQ85AKBMNSrBexRs2js',
    appId: '1:1016127342955:web:25a882bdee92850789642e',
    messagingSenderId: '1016127342955',
    projectId: 'attendease-b941e',
    authDomain: 'attendease-b941e.firebaseapp.com',
    storageBucket: 'attendease-b941e.appspot.com',
    measurementId: 'G-6W2W2X56TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd-SvzTKhnxFsQ_TO1ZcBIhoE9qd3ErrQ',
    appId: '1:1016127342955:android:d93e11e003c385ab89642e',
    messagingSenderId: '1016127342955',
    projectId: 'attendease-b941e',
    storageBucket: 'attendease-b941e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChwsqdQIwxLfTx-euo0be_sOk6PsdVGrg',
    appId: '1:1016127342955:ios:7600513b7abb0e9e89642e',
    messagingSenderId: '1016127342955',
    projectId: 'attendease-b941e',
    storageBucket: 'attendease-b941e.appspot.com',
    iosBundleId: 'com.example.attendease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChwsqdQIwxLfTx-euo0be_sOk6PsdVGrg',
    appId: '1:1016127342955:ios:7600513b7abb0e9e89642e',
    messagingSenderId: '1016127342955',
    projectId: 'attendease-b941e',
    storageBucket: 'attendease-b941e.appspot.com',
    iosBundleId: 'com.example.attendease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc3gBw8pjXAwVwNQ85AKBMNSrBexRs2js',
    appId: '1:1016127342955:web:1eb788dc89c5e63b89642e',
    messagingSenderId: '1016127342955',
    projectId: 'attendease-b941e',
    authDomain: 'attendease-b941e.firebaseapp.com',
    storageBucket: 'attendease-b941e.appspot.com',
    measurementId: 'G-P57RVFY6WQ',
  );
}
